---
epel_release:
  "4": 10
  "5": 4
  "6": 8
  "7": 5

epel_repo_url: " http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-9.noarch.rpm"
epel_repo_gpg_key_url: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7"

